// Copyright 2002-2003 Kenta Cho. All rights reserved.
using System;
using System.Collections.Generic;
using static GameMath;
using static Drawing;
using static RrConstants;
using static RrArrays;
using static RrRandom;
using static RrBarrage;
using static RrSound;
using static RrGl;
using static RrPreference;
using static RrCore;
using static RrAttract;
using static RrShip;
using static RrLaser;
using static RrShot;
using static RrFrag;
using static RrBackground;
using static RrBoss;
using static RrFoe;
using static RrScreen;
using static RrLetter;
using static RrAngles;
using static RrVector;

public static class RrConstants {
public const int MUSIC_NUM = 3;
public const int CHUNK_NUM = 16;
public const int SHOT_MAX = 64;
public const int SHOT_SPEED = 4096;
public const float SHOT_HEIHGT_SPEED = (SHOT_SPEED/FIELD_SCREEN_RATIO);
public const int FIELD_WIDTH = 320;
public const int FIELD_HEIGHT = 480;
public const int FIELD_WIDTH_8 = (FIELD_WIDTH<<8);
public const int FIELD_HEIGHT_8 = (FIELD_HEIGHT<<8);
public const float FIELD_SCREEN_RATIO = 10000.0f;
public const int SHIP_SPEED = 1000;
public const int SHIP_SLOW_SPEED = 500;
public const int SHIP_SLOW_DOWN = 50;
public const int SHIP_ROLLING_SPEED = 300;
public const int SHIP_IKAGW_SPEED = 800;
public const int SHIP_INVINCIBLE_CNT_BASE = 240;
public const int GRZ_WIDTH = 5000;
public const int FLD_WIDTH = 8000;
public const int RF_WIDTH = 10000;
public const int RF_METER_MAX = 2000;
public const int RF_METER_DEC = 50;
public const int RF_METER_INC = 5;
public const int SHOT_INTERVAL = 3;
public const int SHIP_FIELD_WIDTH = 1024;
public const int SHIP_SCREEN_EDGE_WIDTH = 3;
public const int BOMB_SPEED = 1280;
public const int BOMB_UP_SPEED = 128;
public const int BOMB_CNT = 160;
public const int BOMB_NEXT_READY_CNT = 90;
public const int ROLLING_CNT_BASE = 45;
public const int INVINCIBLE_GRZ_NUM = 2000;
public const int INVINCIBLE_GRZ_CNT = 120;
public const int COLOR_CHG_CNT = 20;
public const int ABSENG_CNT = 1;
public const int SHIP_DRAW_WIDTH = 6;
public const float SHIP_DRUM_WIDTH = 0.05f;
public const int SHIP_DRUM_SIZE = 4;
public const int PAD_UP = 1;
public const int PAD_DOWN = 2;
public const int PAD_LEFT = 4;
public const int PAD_RIGHT = 8;
public const int PAD_BUTTON1 = 16;
public const int PAD_BUTTON2 = 32;
public const int DEFAULT_BRIGHTNESS = 224;
public const int FAR_PLANE = 720;
public const int SCREEN_WIDTH = 640;
public const int SCREEN_HEIGHT = 480;
public const int LOWRES_SCREEN_WIDTH = 320;
public const int LOWRES_SCREEN_HEIGHT = 240;
public const string STAR_BMP = "star.bmp";
public const string SMOKE_BMP = "smoke.bmp";
public const string TITLE_BMP = "title.bmp";
public const int LASER_ALPHA = 100;
public const int LASER_LINE_ALPHA = 50;
public const int LASER_LINE_ROLL_SPEED = 17;
public const int LASER_LINE_UP_SPEED = 16;
public const float SHAPE_POINT_SIZE = 0.05f;
public const int SHAPE_BASE_COLOR_R = 250;
public const int SHAPE_BASE_COLOR_G = 240;
public const int SHAPE_BASE_COLOR_B = 180;
public const float CORE_HEIGHT = 0.2f;
public const float CORE_RING_SIZE = 0.6f;
public const float SHAPE_POINT_SIZE_L = 0.07f;
public const float SHIP_DRUM_R = 0.4f;
public const float SHIP_DRUM_HEIGHT = 0.35f;
public const float SHOT_WIDTH = 0.1f;
public const float SHOT_HEIGHT = 0.2f;
public const int JOYSTICK_AXIS = 16384;
public const string CAPTION = "rRootage";
public const int VERSION_NUM = 22;
public const int INTERVAL_BASE = 16;
public const int TITLE = 0;
public const int IN_GAME = 1;
public const int GAMEOVER = 2;
public const int STAGE_CLEAR = 3;
public const int PAUSE = 4;
public const int LASER_MAX = 64;
public const int LASER_SPEED = 4096;
public const int LASER_WIDTH = 4800;
public const int LASER_WIDTH_ADD = 480;
public const int LASER_COLOR_SPEED = 12;
public const float LASER_SCREEN_HEIGHT = (LASER_SPEED/FIELD_SCREEN_RATIO);
public const int NOT_EXIST = -999999;
public const int FRAG_COLOR_NUM = 2;
public const int FRAG_MAX = 512;
public const int FRAG_LINE = 0;
public const int FOE_ENEMY_POS_RATIO = 1024;
public const int BULLET_COLOR_NUM = 4;
public const int BULLET_TYPE_NUM = 3;
public const int COMMAND_SCREEN_SPD_RATE = 512;
public const int COMMAND_SCREEN_VEL_RATE = 512;
public const int BATTERY = 0;
public const int ACTIVE_BULLET = 1;
public const int BULLET = 2;
public const int NOT_EXIST_TMP = (NOT_EXIST-1);
public const int FOE_MAX = 1024;
public const int SHIP_HIT_WIDTH = 300*300;
public const int SLOW_MOVE = 64;
public const int SLOW_MOVE_VANISH_CNT = 60;
public const int LIMITER_VANISH_CNT = 8;
public const int GRZ_METER_UP_ROLLING = 12;
public const int GRZ_METER_UP = 10;
public const int DEFAULT_SPEED_DOWN_BULLETS_NUM = 180;
public const int DIV = 1024;
public const int TAN_TABLE_SIZE = 1024;
public const int SC_TABLE_SIZE = 1024;
public const int MORPH_PATTERN_MAX = 8;
public const int IKA_FIX = 0;
public const int IKA_ALTERNATE = 1;
public const int IKA_HALF = 2;
public const int IKA_ALTERNATE_SHOT = 3;
public const int BATTERY_PATTERN_MAX = 6;
public const int BATTERY_MAX = 3;
public const int BATTERY_GROUP_MAX = 10;
public const int MOVE_POINT_MAX = 4;
public const int COLLISION_NUM = 5;
public const int CREATING = 0;
public const int ATTACKING = 1;
public const int CHANGE = 2;
public const int LAST_ATTACK = 3;
public const int DESTROIED = 4;
public const int DESTROIED_END = 5;
public const int BOSS_WING_MAX = 2;
public const int TREE_MAX_LENGTH = 5;
public const int BOSS_INITIAL_X = 0;
public const int BOSS_INITIAL_Y = (-FIELD_HEIGHT_8/3);
public const int BOSS_PATTERN_CHANGE_CNT = 100;
public const int BOSS_SHIELD = 30000;
public const int BOSS_SHIELD_MAX = 70000;
public const int BOSS_TIMER_COUNT_UP = 17;
public const int BOSS_TIME_UP = (1000*90);
public const int BARRAGE_TYPE_NUM = 6;
public const int BARRAGE_PATTERN_MAX = 32;
public const int NORMAL_BARRAGE = 0;
public const int REVERSIBLE_BARRAGE = 1;
public const int MORPH_BARRAGE = 2;
public const int SIMPLE_BARRAGE = 3;
public const int MORPH_HEAVY_BARRAGE = 4;
public const int PSY_MORPH_BARRAGE = 5;
public const int PLANE_MAX = 4;
public const int STAGE_NUM = 40;
public const int SAME_RANK_STAGE_NUM = 4;
public const int MODE_NUM = 4;
public const int NORMAL_MODE = 0;
public const int PSY_MODE = 1;
public const int IKA_MODE = 2;
public const int GW_MODE = 3;
public const int DEFAULT_HISCORE = 100000;
public const float RANK_UP_BASE = 1.25f;
public const int SCENE_STAT_X = 77;
public const int SCENE_STAT_SIZE = 9;
public const int STG_BOX_SIZE = 21;
public const int STG_BOX_NUM = (MODE_NUM+STAGE_NUM+1);
public const int LAYER_HEIGHT = 480;
public const int QUIT_STAGE_NUM = 40;
}
