<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <LubRoot Condition="'$(LubRoot)' == ''">../../../.cache/lub</LubRoot>
    <BaseOutputPath>../../../build/frame/bin/</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(LubRoot)/dotnet/Lub/Lub.csproj" />
    <ProjectReference Include="$(LubRoot)/third_party/tcs/TinySystem/TinySystem.csproj" />
    <Compile Include="../*.cs" />
    <Compile Include="../../frame/FrameMath.cs" />
    <Compile Include="../../../game/SimulationTime.cs" />
    <Compile Include="../../../game/Mesh.cs;../../../game/Transform.cs;../../../game/Pattern.cs;../../../game/PatternNumber.cs;../../../build/torus-trooper/*.cs" />
    <Content Include="mesh.*.slang" CopyToOutputDirectory="PreserveNewest" Link="%(Filename)%(Extension)" />
    <Content Include="run.sh" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
