<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <BaseOutputPath>../../../build/frame-perf/</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../games/gear-toy-gear/frame/GearToyGear.csproj" />
  </ItemGroup>
</Project>
