<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StartupObject>FrameTests</StartupObject>
    <BaseOutputPath>../../../build/frame-tests/</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../games/torus-trooper/frame/TorusTrooper.csproj" />
    <Compile Include="../GameVerification.cs" />
  </ItemGroup>
</Project>
